-- Emerald work rules seed data (MySQL 8.0+)
-- Run after work_rules_schema.sql

INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('PURPOSE','目的','general','本工作規章旨在制定一套標準作業手冊，供公司全體員工正確遵循，並要求所有員工嚴格遵守。','Emerald_工作規章_繁體中文譯本.pdf',1,1,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('SCOPE','適用範圍','general','本工作規章適用於公司全體員工，內容包括公司所訂定的懲處規定與提供的福利。','Emerald_工作規章_繁體中文譯本.pdf',1,2,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('DEFINITIONS','名詞定義','general','- **生產線員工**：指從事生產、裁切、縫製、封合、包裝、無塵室、品質管制（QC）、倉庫（Store）、清潔及技術維修等工作的員工。
- **辦公室員工**：指固定在辦公室（Office）工作，且不直接參與生產作業的員工。','Emerald_工作規章_繁體中文譯本.pdf',1,3,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('1','第 1 條：求職文件真實性','employment','求職申請所附文件必須真實。如查明有虛假情形，公司將依情節予以適當處分。','Emerald_工作規章_繁體中文譯本.pdf',1,4,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('2','第 2 條：職務調整','employment','員工原則上應執行其固定職務；如公司評估員工具備執行其他職務的能力，公司得視情況適當調整其職位或工作內容。','Emerald_工作規章_繁體中文譯本.pdf',1,5,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('3','第 3 條：上班、午休、下班與加班時間','attendance','上班時間為 08:00；午休時間為 12:00 至 13:00；下班時間為 17:00。加班前休息時間為 17:00 至 17:30，加班自 17:31 起，至雙方約定時間為止，但不得超過法律規定的上限。','Emerald_工作規章_繁體中文譯本.pdf',1,6,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('4','第 4 條：制服、識別證與飾品','workplace','員工進入公司時，必須穿著公司提供的制服，並於每次上班前佩戴員工識別證。進入生產部門時，禁止佩戴戒指、耳環、手環等飾品。','Emerald_工作規章_繁體中文譯本.pdf',1,7,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('5','第 5 條：尚未領取制服者的服裝規定','workplace','尚未領取制服的員工，服裝應端莊整潔並便於工作。生產部門男女員工均須穿白色上衣，不得穿細肩帶、無袖或過度透薄的上衣；下身須穿長褲，不得穿短褲、五分褲、七分褲、緊身褲或色彩過於鮮豔的褲子進入公司。辦公室女性員工可穿裙子上班，但不得過短，款式與顏色應端莊得體。','Emerald_工作規章_繁體中文譯本.pdf',2,8,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('6','第 6 條：生產線制服、帽子、指甲與鞋子','workplace','生產線員工上班時，必須依公司規定穿著制服及帽子；指甲須經常修剪並保持短而清潔；並須穿著公司提供的鞋子，且隨時保持工作服與鞋子的清潔。','Emerald_工作規章_繁體中文譯本.pdf',2,9,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('7','第 7 條：生產部門禁止攜入物品','workplace','生產線員工嚴禁將食物、水、零食、飯食或個人物品帶入生產部門，例如粉餅、口紅、口服藥、外用藥及行動電話等。','Emerald_工作規章_繁體中文譯本.pdf',2,10,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('8','第 8 條：吸菸','discipline','公司僅允許在指定地點吸菸；未依規定辦理者，視為嚴重違反紀律。','Emerald_工作規章_繁體中文譯本.pdf',2,11,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('9','第 9 條：酒類、致醉飲品、毒品與賭博','discipline','嚴禁在工廠內飲酒、飲用其他致醉飲品、施用毒品或賭博；亦禁止攜帶、買賣酒類或毒品。如經查獲，將立即終止員工身分，並由公司報警依法處理。處於醉酒狀態或身體狀況不適合工作的員工，當日不得進入公司上班。','Emerald_工作規章_繁體中文譯本.pdf',2,12,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('10','第 10 條：危險武器','discipline','嚴禁攜帶危險武器進入公司或生產部門。如經查獲，將終止員工身分，並由公司報警依法處理。','Emerald_工作規章_繁體中文譯本.pdf',2,13,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('11','第 11 條：鬥毆與衝突','discipline','嚴禁在公司內鬥毆或引發衝突；如經查獲，視為違規並終止員工身分。','Emerald_工作規章_繁體中文譯本.pdf',2,14,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('12','第 12 條：兵役文件','employment','已完成兵役義務的男性員工，應配合提交相關文件供公司留存。尚未到服役期限或依法緩徵者，亦須提出證明文件或事先通知公司。如公司查明未依規定辦理，將視為違規並終止員工身分。','Emerald_工作規章_繁體中文譯本.pdf',2,15,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('13','第 13 條：公司名譽、財產、舞弊、資料與工作損失','discipline','如員工造成公司名譽或財產受損、涉及舞弊，或洩漏公司資料，以及因故意或疏忽造成工作錯誤或公司損失，均視為違規；公司將依實際損害的嚴重程度，酌情決定處分。','Emerald_工作規章_繁體中文譯本.pdf',2,16,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('14','第 14 條：公司文件與公告','employment','公司文件、公告板及公告均屬公司財產；員工如有毀損或違反相關規定，視為違規。','Emerald_工作規章_繁體中文譯本.pdf',2,17,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('15','第 15 條：試用期','employment','試用期為 119 天，且員工必須通過公司的工作評估。未達評估標準者，視為未通過試用期，後續處理由公司決定。','Emerald_工作規章_繁體中文譯本.pdf',2,18,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('16.1.1','16.1.1 病假 1 天','sick_leave','請病假 1 天時，員工須於當日上午 09:00 前先通知公司。請假方式及應附文件如下：

1. 員工本人須於 09:00 前致電通知直屬主管及人力資源部門，以避免影響連續性工作。
2. 應提供由具合法資格之現代醫學醫師開立的醫療證明（如有，應提交正本）。
3. 返回工作崗位後，員工須於 24 小時內完成請假單。','Emerald_工作規章_繁體中文譯本.pdf',3,19,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('16.1.2','16.1.2 病假 2 天以上','sick_leave','病假達 2 天以上者，僅接受醫院內具合法資格之現代醫學醫師開立的醫療證明；員工並須每天於 09:00 前致電通知直屬主管及人力資源部門，直到能恢復正常上班為止。','Emerald_工作規章_繁體中文譯本.pdf',3,20,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('16.2.1','16.2.1 事假 1 天','personal_leave','請事假 1 天，須至少提前 2 天提出申請。若屬緊急事件，須於 09:00 前致電通知直屬主管及人力資源部門，以避免影響連續性工作；返回上班當日並須於 24 小時內完成請假單。','Emerald_工作規章_繁體中文譯本.pdf',3,21,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('16.2.2','16.2.2 事假 2 天以上','personal_leave','請事假 2 天以上，須至少提前 7 天提出申請。

**事假備註**：每年事假不得超過 6 天；事假當日不支薪。每次請事假均須附具相關證明，供公司重新審酌是否適當。','Emerald_工作規章_繁體中文譯本.pdf',3,22,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('16.3.1','16.3.1 年假申請與額度','annual_leave','員工自到職日起，依比例取得年假權利，每年最多 6 天。每次可申請 1 天，須提前 7 天通知；每月最多可請 2 天。年假須於當年度使用，不得累積至次年度。公司保留核准或不核准之權利。

**病假、事假與年假共同備註**：

- 第 16.1、16.2 及 16.3 項所列假別，均須經公司核准後方可休假。
- 不得於國定假日前後連續請假，例如在假日前後的星期六或星期一請假。
- 每次請假均會影響全勤獎金及特別獎金。
- 病假或緊急事假須於 09:00 前通知人力資源部門，並在返回上班當日的 24 小時內完成請假單。
- 未獲公司核准而當日未到班者，公司將視為曠職。','Emerald_工作規章_繁體中文譯本.pdf',3,23,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('16.4.1','16.4.1 生產部門員工','resignation','適用於生產部門員工，主管級除外；主管級依第 16.4.2 項辦理。

- 任職未滿 90 天：須提前 3 天提出離職通知。
- 任職滿 90 天以上：須提前 15 天提出離職通知。
- QC、CN、M&E、ST 等按日計薪人員，或在辦公室工作者：須提前 30 天提出離職通知。','Emerald_工作規章_繁體中文譯本.pdf',3,24,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('16.4.2','16.4.2 非生產部門、財產／財務責任及按月計薪員工','resignation','- 任職未滿 90 天：須提前 15 天提出離職通知。
- 任職超過 90 天：須提前 30 天提出離職通知。
- 任職滿 1 至 2 年：須提前 45 天提出離職通知。
- 任職滿 2 至 4 年：須提前 60 天提出離職通知。
- 任職滿 4 年以上：須提前 90 天提出離職通知。

**離職備註**：公司保留依個別情況判斷是否適當之權利。','Emerald_工作規章_繁體中文譯本.pdf',4,25,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('17','第 17 條：警告處分','discipline','員工未遵守公司規章時，公司得依情況記錄違規並發出警告，處理方式如下：

1. 第 1 次警告：口頭警告（另作書面紀錄）。
2. 第 2 次警告：視為第二級違規警告。
3. 第 3 次警告：停職 3 天，或由公司視情況決定更長的停職期間。
4. 第 4 次警告：終止員工身分。

**備註**：如員工收到警告單但拒絕簽名承認，公司將在公告板張貼至少 1 天，以通知員工該行為違反公司規章，防止再犯，並避免其他員工仿效。','Emerald_工作規章_繁體中文譯本.pdf',4,26,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('18','第 18 條：連續假期後到班與國定假日前後請假','discipline','公司連續放假多日時，員工必須於公司指定恢復上班之日到班；不得在國定假日前後請假。','Emerald_工作規章_繁體中文譯本.pdf',4,27,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('19','第 19 條：已同意加班後未到班、取消與代簽','attendance','如公司已事先通知加班，且員工已簽名同意並申請加班，但之後未到班加班，將視為違規。員工如需取消或請假不加班，須於 15:00 前通知人力資源部門，由其轉知公司。加班同意僅能由本人簽名，嚴禁代他人簽名；代簽行為屬違反紀律，將依違規情節處分。','Emerald_工作規章_繁體中文譯本.pdf',4,28,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('20','第 20 條：刷卡與代刷卡','attendance','所有員工均須依公司規定刷卡，以記錄工作時間；嚴禁代他人刷卡。如屬故意代刷，雙方均將被終止員工身分，因該行為視為對公司的舞弊。','Emerald_工作規章_繁體中文譯本.pdf',4,29,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('21','第 21 條：遲到','attendance','遲到 1 至 15 分鐘，累計 3 次者，發給 1 張警告單。遲到 30 分鐘以上者，將扣除其原可享有的福利，並須於 24 小時內完成請假單。','Emerald_工作規章_繁體中文譯本.pdf',4,30,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('22','第 22 條：生產區域的行動電話、相機與通訊設備','workplace','行動電話、相機及各類通訊設備，禁止帶入生產區域或公司指定區域；經個別授權者除外。如經查獲，視為嚴重違反紀律。','Emerald_工作規章_繁體中文譯本.pdf',4,31,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('23','第 23 條：公開平台、公司資料、照片與生產資訊','discipline','未經公司書面同意，無論是否出於故意，均不得在公開平台發布侮辱性文字，或揭露、散布公司的資料、照片、地點、產品、生產流程、設備、工具或機械等資訊；違者視為嚴重違反紀律。','Emerald_工作規章_繁體中文譯本.pdf',4,32,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('24','第 24 條：工作時間使用行動電話與私人事務','workplace','工作時間內禁止玩行動電話、傳送與工作無關的私人訊息，或處理私人事務；如因此降低工作效率或干擾他人工作，視為違反紀律。','Emerald_工作規章_繁體中文譯本.pdf',4,33,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('25','第 25 條：公司電腦、設備、軟體與財產攜出','discipline','公司提供的各類財產，包括桌上型電腦（PC）、筆記型電腦（Notebook）、iPad 及其他設備，僅供工作使用，不得用於娛樂；亦不得擅自改裝、增添或移除設備，或安裝、使用未經許可的軟體。上述行為視為嚴重違反紀律。將公司財產帶離工廠區域時，每次均須事先取得許可。','Emerald_工作規章_繁體中文譯本.pdf',5,34,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('26','第 26 條：安全規章','discipline','所有員工均須嚴格配合並遵守公司的安全規章。','Emerald_工作規章_繁體中文譯本.pdf',5,35,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('BENEFITS','員工福利','benefits','公司為員工提供的福利如下：

1. 每月全勤獎金。
2. 社會保險。
3. 任職滿 1 年後，公司提供制服 1 件及鞋子 1 雙。
4. 提供 1 格置物櫃，以確保個人物品安全。
5. 每日午餐時段的餐費補助。
6. 加班時段的餐費補助。
7. 年度聯誼或聚餐活動及禮品。','Emerald_工作規章_繁體中文譯本.pdf',5,36,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('CERTIFICATIONS','公司取得的認證標準','company','公司已取得 ISO 13485 及 MDD 93/42/EEC 認證。','Emerald_工作規章_繁體中文譯本.pdf',5,37,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
INSERT INTO work_rules (code,title,category,content_zh,source_document,source_page,sort_order,active) VALUES ('QUALITY_POLICY','公司品質政策','company','- 品質符合需求
- 準時交付
- Emerald 持續致力於發展與改善
- 因為客戶是最重要的人

上述公司工作規章經審議後，認定內容適當。受僱人已詳盡閱讀並理解本規章，特此簽名作為重要證明。','Emerald_工作規章_繁體中文譯本.pdf',5,38,1) ON DUPLICATE KEY UPDATE title=VALUES(title), category=VALUES(category), content_zh=VALUES(content_zh), source_document=VALUES(source_document), source_page=VALUES(source_page), sort_order=VALUES(sort_order), active=1, updated_at=CURRENT_TIMESTAMP;
